### ISSUE TITLE
I want to change the highlight color

### ISSUE THREAD

**Issue by AgoN-jorrvaskr** [hipstersmoothie/github-dark-high-contrast#2]
I have attached an image, but it is very difficult to see the highlighted areas because they are completely white.
I would like to change the color to my liking, but where in the GitHub Dark High Contrast JSON file should I change it?
![スクリーンショット 2024-01-04 165036](https://github.com/hipstersmoothie/github-dark-high-contrast/assets/95260275/833bc92f-7d8f-4f42-ba0e-97ecb55734c3)

**Comment by hipstersmoothie** [comment]
If you want to submit a PR fixing that I would accept!
